test:
  build: ../ ../ 
  dockerfile: docker/dev/dockerfile
  volumes_from:
    -cache
  links: 
    -db
  environment:
    DJANGO_SETTING_MODULE: todobackend.settings.test
    MYSQL_HOST: db 
    MYSQL_USER: root
    MYSQL_PASSWORD: MYSQL_PASSWORD
    TEST_OUTPUT_DIR: /reports 

db:
  image: mysql:5.6
  hostname: db
  expose:
    -"3306"
  environment:
    MYSQL_ROOT_PASSWORD: password 
    
cache:
  build: ../ ../ 
  dockerfile: docker/dev/dockerfile
  volumes: 
    - /tmp/cache:/cache
  entrypoint: "true" 
